---
jobs:
- name: update-industryday-website
  public: true
  serial: true
  plan:
  - get: git-industryday-website
    trigger: true
  - task: rebuild-mkdocs
    config:
      platform: linux
      image: "docker:///metal3d/mkdocs"
      inputs:
      - name: git-industryday-website
      outputs:
      - name: mkdocs-output
      run:
        path: sh
        args:
        - -exc
        - |
          cp -r git-industryday-website/* mkdocs-output
          cd mkdocs-output
          mkdocs build
  - put: industryday-website
    params:
      manifest: mkdocs-output/manifest.yml
      path: mkdocs-output/site

resources:
- name: git-industryday-website
  type: git
  source:
    uri: https://github.com/cf-platform-eng/pivotalcf-industry-day.git

- name: industryday-website
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{pws-username}}
    password: {{pws-password}}
    organization: {{pws-org}}
    space: {{pws-space}}
    skip_cert_check: false
